FROM nginx
RUN apt update && apt-get install -y locales
 
# Locale
RUN sed -i -e \
  's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen \
   && locale-gen
 
ENV LANG ru_RU.UTF-8
ENV LANGUAGE ru_RU:ru
ENV LC_LANG ru_RU.UTF-8
ENV LC_ALL ru_RU.UTF-8
 
RUN  mkdir /var/www
RUN  rm -f /etc/nginx/conf.d/default.conf
COPY site.conf  /etc/nginx/conf.d/
COPY site/. /var/www/
RUN  chown nginx:nginx -R /var/www/



#####################site.conf#####################
> server {
>     server_name 172.23.26.88;
>     access_log /var/log/nginx_access.log;
>     error_log /var/log/nginx_error.log;
>     root /var/www;
>     location / {
>                 index  index.html index.htm index.php;
>     }
> }
