
# 'node' official image, with the alpine 6.x branch (node:6-alpine)
FROM node:6-alpine
  
# this app listens on port 3000, but the container should launch on port 80
  #  so it will respond to http://localhost:80 on your computer
EXPOSE 3000
# use alpine package manager to install tini: 'apk add --no-cache tini'
RUN apk add --update tini
# create directory /usr/src/app for app files with 'mkdir -p /usr/src/app'
RUN  mkdir -p /usr/src/app
WORKDIR /usr/src/app
# - Node uses a "package manager", so it needs to copy in package.json file
COPY package.json package.json
# run 'npm install' to install dependencies from that file
RUN npm install && npm cache clean
# copy in all files from current directory
COPY . .
# start container with command '/sbin/tini -- node ./bin/www'
CMD ["/sbin/tini", "--", "node", "./bin/www"]


